name: Unzip Archive

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Unzip the archive
      run: |
        for archive in $(find . -name "*.zip"); do
          unzip $archive -d $(dirname $archive)
        done

    - name: Commit unzipped files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Unzipped archive files"
        git push
